### PR TITLE
fix(BUX-218): do not send access key revoked at if it is not revoked

### PR DESCRIPTION
**Pull request by dorzepowski**
ℹ️  depends on [changes in bux-models](https://github.com/BuxOrg/bux-models/pull/6)

### CODE REVIEW

**Review by wregulski — APPROVED** [review]

**Review by pawellewandowski98 — APPROVED** [review]

**Review by vitalibalashka — APPROVED** [review]

**Review by mrz1836 — APPROVED** [review]
LGTM

**Review by mrz1836 — CHANGES_REQUESTED** [review]
Merge conflict needs to be resolved

**Comment by dorzepowski** [comment]
> @dorzepowski @wregulski @vitalibalashka there is a merge conflict that needs to be resolved.

Conflict resolved

**Comment by mrz1836** [comment]
Thanks @dorzepowski but looks like you need to run `make update` or something similar, the go.sum is not liking the bux models new version

**Comment by dorzepowski** [comment]
> Thanks @dorzepowski but looks like you need to run `make update` or something similar, the go.sum is not liking the bux models new version

@mrz1836 right, I can't do that previously, because v0.2.0 doesn't exist, now it is updated

**Pull request merged**
